---
name: Plan - network

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/network/*'
      - '.github/workflows/plan-network.yaml'
      - '.github/workflows/reusable-ci-workflow.yaml'
  workflow_dispatch:

jobs:
  ## run terraform plan
  plan_network:
    name: Network
    uses: "./.github/workflows/reusable-ci-workflow.yaml"
    with:
      module_path: network
      aws_region: us-east-2
      dev: true
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write








