---
name: Plan - db

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/db/*'
      - '.github/workflows/plan-db.yaml'
      - '.github/workflows/reusable-ci-workflow.yaml'
  workflow_dispatch:

jobs:
  ## run terraform plan
  plan_db:
    name: DB
    uses: "./.github/workflows/reusable-ci-workflow.yaml"
    with:
      module_path: db
      aws_region: us-east-1
      dev: true
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write







