---
name: Plan - eks

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/eks/*'
      - '.github/workflows/plan-eks.yaml'
      - '.github/workflows/reusable-ci-workflow.yaml'
  workflow_dispatch:

jobs:
  ## run terraform plan
  plan_eks:
    name: EKS
    uses: "./.github/workflows/reusable-ci-workflow.yaml"
    with:
      module_path: eks
      aws_region: us-eastt-1
      dev: true
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write







